### ISSUE TITLE
Board specific source examples

### ISSUE THREAD

**Issue by justiceamoh** [sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs#12]
Thanks for putting together BSPs for the Sparkfun Artemis boards. 

I am trying to create my own project for Redboard Artemis but the Makefiles for the examples provided all use sources from the `boards_sfe/common` directory, rather than inside the project folder itself. I attempted tweaking the Makefiles to refer to srcs within the project directory but I keep getting make errors. 

My goal: overall, I'm trying to keep the SDK in a fixed location (home directory), while keeping projects in a different location but ensuring the Makefile can point to the SDK.

**Comment by oclyke** [comment]
Hi @justiceamoh -- I also like to organize my projects that way and that''s why I tailored the makefiles the way they are now. I'll see if I can point you in the right direction.

I'll just write the steps that I take when making a brand-new project in a remote directory (assuming you already have the necessary tools and SDK installed)

* create the example directory and a directory in which to store gcc related items
``` bash
mkdir -p ~/$ANYPATH/example/gcc
cd example
```
* copy the makefile template to the gcc folder
``` bash
cp $BSP_PATH/
```
* add your own file structure under the example -- in this case I will use:
example
. src
.. inc1.h
.. inc1.c
. main.c
* write your source code (main.c, inc1.h, inc1.c etc... I'd recommend using a ```main.c``` from the BSP as a starting point)
* now use your favorite text editor to modify the Makefile
  * add any necessary ```DEFINES```
  * add any directories with ```.h``` files in them to the ```INCLUDES``` path using an appropriate path (for example ```INCLUDES+= -I$(PROJECTPATH)/src``` because ```inc1.h``` is under ```src``` which is in my project directory ```example```)
  * add any additional source files to ```SRC``` (for example ```inc1.c```)
  * add paths to source files in the ```VPATH``` variable (the template makefile already specifies ```$(PROJECTPATH)/src``` as a ```VPATH``` entry, but in our example main.c is directly under ```$(PROJECTPATH)``` so we need to add that like this  ```VPATH+= $(PROJECTPATH)```)
  * if you have pre-compiled libraries (.a files) then you can add them to ```LIBS``` (full path required, you can use the four relative path definitions) 
* enter the gcc directory ``` cd gcc```
* now we will need to call the Makefile with the proper relative paths
  1. permanently fix the paths in the Makefile on these lines
``` Makefile
SDKPATH				?=# Set as the path to the SDK root if not located at ../../../../..
COMMONPATH			?=# Set as the path to the BSP if not located at ../../../../common
BOARDPATH			?=# Set as the path to the board if not located at ../../..
PROJECTPATH			?=# Set as the path to the project if not located at ../..
``` 
  1. override the paths on the command line like this (make sure to use the correct forward/backward slashes for your system):
``` make SDKPATH=$YOUR_SDK_PATH COMMONPATH=$YOUR_COMMON_PATH BOARDPATH=$YOUR_BOARD_PATH PROJECTPATH=$YOUR_PROJECT_PATH ```

Here are the relative path definitions

``` bash 
SDKPATH # this is the path to the root of the AmbiqSuite SDK
COMMONPATH # this is the path to the common directory within the BSP repo
BOARDPATH # this is the path to the directory that contains the bsp directory for the board you want to use
PROJECTPATH # this is the path to the directory above gcc
```

You can also override the values for 
``` Makefile
COM_PORT
ASB_UPLOAD_BAUD
SVL_UPLOAD_BAUD
PYTHON3
```

**Comment by justiceamoh** [comment]
Thank you so much! Very helpful, I was able to build my project successfully. However, when I'm uploading using the SVL bootloader, I get the following:
```
Artemis SVL Bootloader

phase:	setup
	cleared startup blip
	Got SVL Bootloader Version: 3
	Sending 'enter bootloader' command

phase:	bootload
	have 0 bytes to send in 0 frames

	Upload complete
```

But no code is actually uploaded. I tried reducing the baud rate down to 115200 but still no luck. Do you have any suggestions?

**Comment by oclyke** [comment]
Hmmm.... since it says 
```
have 0 bytes to send in 0 frames
```
I suspect that there is a problem with the binary file. How did you invoke the uploader? If you used it manually you should double check that the binary file exists and is non-zero size, and that you're passing it in correctly to the tool. If you used ```make bootload``` then there might be some kind of hiccup in the makefile. You could inspect it and make sure that the dependency of the bootload step matches the target that links the files together into the final .bin. Also make sure the filepath listed there matches the output of the linking step.

Let me know how that goes for you!

**Comment by justiceamoh** [comment]
Ah you're right. The binary files, `example_asb.bin` and `example_svl.bin` are both just 0 bytes. Although `example_svl.axf` files are not zero. I invoked the bootloader with `make bootload`.

Hmm, I didn't have any errors during compilation though. Just a warning:
` Linking gcc bin/example_asb.axf with script /Users/Justice/AmbiqSDK/boards_sfe/common/tools_sfe/templates/asb_linker.ld
/usr/local/Cellar/arm-none-eabi-gcc/8-2018-q4-major/gcc/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol Reset_Handler; defaulting to 000000000000c000`

**Comment by oclyke** [comment]
Okay - the .bin files are dependent on the .axf files and we use arm-none-eabi-objcpy to transform the formats from one to another. If the .bin files already existed and there were no changes to dependency files then it is possible they might not be regenerated. 

To see if they are in fact being generated do this:
* run ```make clean```
* verify that build files are removed from the ```bin``` directory
* run either ```make bootload_asb``` or ```make bootload_svl``` depending on which upload tool you want to use
* verify that both the ```.axf``` as well as the ```.bin``` files are created. 

If they are in fact created fresh by ```make``` then we will need to investigate further why the ```.bin``` file has zero size.

**Comment by justiceamoh** [comment]
Thanks for the prompt response @oclyke. I have run `make clean` a number of times but I still get a zero byte `.bin` file generated by the Makefile. However, the `.axf` file is not empty - 796 bytes, in my case. I even deleted the whole bin directory but still observed the same thing.

**Comment by justiceamoh** [comment]
I tried to manually generate the `.bin` file with: 
`arm-none-eabi-objcopy -O binary example_svl.axf example_svl.bin`
The resulting file was zero bytes as well.

**Comment by oclyke** [comment]
oof... 796 bytes just seems far too small. There must be something else going on here. Perhaps the compiler is pruning some code that is inaccessible (say for example if the Reset_Handler was wrongly specified -- the main loop might even be pruned). 

Can you clean everything, do a new build, and share the entire output?

Also if you could somehow convey the contents of the project file structure and the makefle you've created that could be helpful.

**Comment by justiceamoh** [comment]
I think you're right -- the bin file from SparkFun examples are at least >100kb when compiled and my sample project is just a basic hello world script with dummy includes. I'm sure there's something wrong with my source or makefile.  

 Here's [a link to the modified makefile](https://pastebin.com/NUe6Z8EV) and another to the [main.c](https://pastebin.com/i3zgEdpd) (modified from SparkFun Edge template). 

And here is the entire output of the make:
```
Makefile:120: warning: you have not defined COM_PORT. Assuming it is COM4
Makefile:124: warning: you have not defined PYTHON3. assuming it is accessible by 'python3'
Makefile:128: defaulting to 115200 baud for ASB
Makefile:132: defaulting to 921600 baud for SVL
 Compiling gcc ../src/main.c
 Compiling gcc ../src/inc1/inc1.c
 Compiling gcc ../src/inc2/inc2.c
 Linking gcc bin/example_asb.axf with script /Users/Justice/AmbiqSDK/boards_sfe/common/tools_sfe/templates/asb_linker.ld
/usr/local/Cellar/arm-none-eabi-gcc/8-2018-q4-major/gcc/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol Reset_Handler; defaulting to 000000000000c000
 Copying gcc bin/example_asb.bin...
```

**Comment by oclyke** [comment]
Okay I think we will have a solution now -- this warning is an indication that the code does not know how to start up. Cause is that your makefile does not list ```startup_gcc.c``` as a SRC. You can either refer to it by the COMMONPATH or use a local copy

``` makefile
...
SRC+= startup_gcc.c
...

# for referencing the BSP copy
VPATH+= $(COMMONPATH)/tools_sfe/templates

# or for using a project folder with a copy of startup_gcc.c
VPATH+= $(PROJECTPATH)/path_to_startup_gcc
```

The warning should go away and the binary should be nonzero size (fingers crossed)

**Comment by justiceamoh** [comment]
You were right! Thank you so much. It uploads now and functions just as expected. I also had to include some of the other startup files: 
```
SRC+= startup_gcc.c
SRC+= am_util_delay.c
SRC+= am_util_faultisr.c
SRC+= am_util_id.c
SRC+= am_util_stdio.c
```
They were all already listed in the original Makefile but I took them out thinking they were project specific -- tsk tsk. Thank you for your time and assistance -- much appreciated.

**Comment by oclyke** [comment]
@justiceamoh Glad it worked out! I usually start with a clean slate myself just so I know that the project is as lean as possible.
