### ISSUE TITLE
C++ Compilation Issue with startup_gcc.c

### ISSUE THREAD

**Issue by justiceamoh** [sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs#14]
Using the Sparkfun provided Makefile for the Artemis Nano board, I am attempting a C++ build because I have a number of C++ libraries I'd like to use. I changed my main source from `main.c` to `main.cpp`. However, when i run `make`, I get the error:
```
bin/startup_gcc.o: in function `Reset_Handler':
startup_gcc.c:291: undefined reference to `main'
```
I think this is because the `startup_gcc.c` file is in C and the compiler, somehow, does not like that. Any ideas how to go about fixing this? 

I've tried declaring the main as `extern "C" int main(void)`, as was done in main.cpp of the Apollo3 Arduino core. Still no luck.

**Comment by oclyke** [comment]
@justiceamoh shoot, I was about to suggest declaring the main function as ```extern "C"```. 

This is a linker error right? I.e. all the required source files are compiled but during the link stage it says there is an undefined reference to ```main()```

Link errors like this are usually cause by one of two things in my experience:
a) name mangling. Files with the ```.cpp``` extension get compiled as C++ and without the ```extern "C"``` magic the name will get adjusted (this is how C++ handles function overloading)
b) necessary objects not included in the link. Either because the source file is not compiled or because the resulting object file is not included in the link step (but if the source is compiled then the ```.o``` is usually linked automatically thanks to the Makefile) Is your ```main.cpp``` being compiled at all? Did you change the name to ```main.cpp``` in the list of ```SRC```'s in the Makefile?

If none of that works you'll have to make sure the symbol for ```int main(void)``` is defined. You can do that by listing the names with the ```arm-none-eabi-nm``` tool.

**Comment by justiceamoh** [comment]
You're right @oclyke. I don't think the `main.cpp` file is getting compiled at all because there is no `main.o` and `arm-none-eabi-nm` shows `main` is undefined. 

I did change the name to `main.cpp` in the list of `SRC`s of the Makefile. However, I have a feeling it's being filtered out. These lines in the Makefile seem to be filtering only c files:
```Makefile
CSRC = $(filter %.c,$(SRC))
ASRC = $(filter %.s,$(SRC))

OBJS = $(CSRC:%.c=$(CONFIG)/%.o)
OBJS+= $(ASRC:%.s=$(CONFIG)/%.o)

DEPS = $(CSRC:%.c=$(CONFIG)/%.d)
DEPS+= $(ASRC:%.s=$(CONFIG)/%.d)
```

I added the following lines to catch CPP files:
```Makefile
CPPS = $(filter %.cpp,$(SRC))
OBJS+= $(CPPS:%.cpp=$(CONFIG)/%.o)
DEPS+= $(CPPS:%.cpp=$(CONFIG)/%.d)
```

And I also included the make rule below to compile the CPP objects: 
```Makefile
$(CONFIG)/%.o: %.cpp $(CONFIG)/%.d
	@echo " Compiling $(COMPILERNAME) $<" ;\
	$(CC) -c $(CFLAGS) $< -o $@
```

I'm still getting linker errors though about [undefined reference to seemingly basic functions](https://pastebin.com/QetpZXu3). I'm not proficient in Make so I am probably missing something. Here's [a gist of my Makefile](https://gist.github.com/justiceamoh/2948a0b6ff5b2b6d33cd2a2b131f9444). It is a slimmed down version of the Sparkfun Apollo3 Makefile you provided. Please let me know if you have any suggestions.

**Comment by justiceamoh** [comment]
I figured it out. I had to compile the the C++ sources separately using `arm-none-eabi-g++`. Some additional flags were necessary for g++ to address some linking issues. I've updated my [Makefile](https://gist.github.com/justiceamoh/2948a0b6ff5b2b6d33cd2a2b131f9444), should it be useful for anyone else.
