### ISSUE TITLE
Timing issues on linux with ambiq_bin2board.py

### ISSUE THREAD

**Issue by suphoff** [sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs#20]
Increasing wait time to 8ms in the line referenced below allows updating the FW on linux/ubuntu.
The issue has been observed on a desktop ubuntu-18.04 with custom serial driver and a 19.10 laptop with default driver.  

Boards tested on desktop: ATP, nano - on Laptop: nano

https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/blob/d3bce998e31f75323401e2bcd7b05eaf403ec8c2/common/tools_sfe/ambiq/ambiq_bin2board.py#L421

Maybe try different timeout values on retries if no value works for all platforms/boards?

**Comment by oclyke** [comment]
I like that idea. 

There is a fairly large backlog of work to be done on the Apollo3/Artemis platform. Bootloader improvements are a big one (second only to BLE and perhaps the TFLM PR). When we get a chance to improve the bootloader I will consider incorporating this. 

To shed a little more light on this for anyone who stumbles across it:
That delay is meant to match an RC circuit that controls the hardware ```boot``` pin on the Apollo3. This is the feature that allows for hands-free UART flashing (otherwise a manual procedure like the one used on the original Edge board would be required). Perhaps there is variability in the execution speed or overhead in that region that causes the timing to fail. I'm not familiar enough to know if the 3ms difference is a reasonable error for the Python ```time.sleep()``` function or the bookend operations.  

Thanks for the report!

**Comment by oclyke** [comment]
P.s. I just made this modification to my script because I was having trouble (Windows 10, RedBoard Artemis ATP) and it significantly improved reliability.
